
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://outtmzncozzjixlpvfbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91dHRtem5jb3p6aml4bHB2ZmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDIwMDIsImV4cCI6MjA1NzM3ODAwMn0.GHEvJZai0ullcY4YhYzJkJ_I55XTd8dWO1gAPZ38v_g";

// Helper function to get base URL that works in both development and production
const getBaseUrl = () => {
  if (typeof window !== 'undefined') {
    // Client-side - use current URL origin
    return window.location.origin;
  }
  // Server-side (should not happen in Vite, but included for completeness)
  return 'https://your-production-domain.com';
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      flowType: 'pkce',
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    }
  }
);

// Add redirectTo configuration to auth.signIn() calls instead of here
